# Set this to your lobby worlds!

Worlds:
  - 'lobby'

# Permissions;
# lobbyfly.use - Gives permission to use "/fly" command
# lobbyfly.admin - Gives permission to use "/lfreload" and "/lfconfig" command

# Commands;
# /fly - Used to enable/disable fly
# /lfreload - Used to reload this plugin
# /lfconfig - Used to see what worlds are set in your config